---
deploy:
  tasks:
    - export DEPLOYPATH=/home/sohanthink/public_html
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp vite.config.js $DEPLOYPATH
    - /bin/cp .eslintrc.cjs $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/chown -R sohanthink:sohanthink $DEPLOYPATH
  metadata:
    version: 1
